const LARGEST_US_CITIES = [
    "New York City",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "Indianapolis",
    "San Francisco",
    "Seattle",
    "Denver",
    "Washington",
    "Nashville",
    "Oklahoma City",
    "Boston",
    "El Paso",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Detroit",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Fresno",
    "Tucson",
    "Sacramento",
    "Kansas City",
    "Mesa",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Long Beach",
    "Virginia Beach",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Bakersfield",
    "Wichita",
    "Arlington",
    "Aurora",
    "Tampa",
    "New Orleans",
    "Cleveland",
    "Honolulu",
    "Anaheim",
    "Louisville",
    "Henderson",
    "Lexington",
    "Irvine",
    "Stockton",
    "Orlando",
    "Corpus Christi",
    "Newark",
    "Riverside",
    "St. Paul",
    "Cincinnati",
    "San Juan",
    "Santa Ana",
    "Greensboro",
    "Pittsburgh",
    "Jersey City",
    "St. Louis",
    "Lincoln",
    "Durham",
    "Anchorage",
    "Plano",
    "Chandler",
    "Chula Vista",
    "Buffalo",
    "Gilbert",
    "Madison",
    "Reno",
    "North Las Vegas",
    "Toledo",
    "Fort Wayne",
    "Irving",
    "Lubbock",
    "St. Petersburg",
    "Laredo",
    "Chesapeake",
    "Winston-Salem",
    "Glendale",
    "Garland",
    "Scottsdale",
    "Arlington",
    "Enterprise",
    "Boise",
    "Santa Clarita",
    "Norfolk",
    "Fremont",
    "Spokane",
    "Richmond",
    "Baton Rouge",
    "San Bernardino",
    "Tacoma",
    "Spring Valley",
    "Hialeah",
    "Huntsville",
    "Modesto",
    "Frisco",
    "Des Moines",
    "Yonkers",
    "Port St. Lucie",
    "Moreno Valley",
    "Worcester",
    "Rochester",
    "Fontana",
    "Columbus",
    "Fayetteville",
    "Sunrise Manor",
    "McKinney",
    "Little Rock",
    "Augusta",
    "Oxnard",
    "Salt Lake City",
    "Amarillo",
    "Overland Park",
    "Cape Coral",
    "Grand Rapids",
    "Huntington Beach",
    "Sioux Falls",
    "Grand Prairie",
    "Montgomery",
    "Tallahassee",
    "Birmingham",
    "Peoria",
    "Glendale",
    "Vancouver",
    "Providence",
    "Knoxville",
    "Brownsville",
    "Akron",
    "Newport News",
    "Fort Lauderdale",
    "Mobile",
    "Shreveport",
    "Paradise",
    "Tempe",
    "Chattanooga",
    "Cary",
    "Eugene",
    "Elk Grove",
    "Santa Rosa",
    "Salem",
    "Ontario",
    "Aurora",
    "Lancaster",
    "Rancho Cucamonga",
    "Oceanside",
    "Fort Collins",
    "Pembroke Pines",
    "Clarksville",
    "Palmdale",
    "Garden Grove",
    "Springfield",
    "Hayward",
    "Salinas",
    "Alexandria",
    "Paterson",
    "Murfreesboro",
    "Bayamon",
    "Sunnyvale",
    "Kansas City",
    "Lakewood",
    "Killeen",
    "Corona",
    "Bellevue",
    "Springfield",
    "Charleston",
    "Hollywood",
    "Roseville",
    "Pasadena",
    "Escondido",
    "Pomona",
    "Mesquite",
    "Naperville",
    "Joliet",
    "Savannah",
    "Jackson",
    "Bridgeport",
    "Syracuse",
    "Surprise",
    "Rockford",
    "Torrance",
    "Thornton",
    "Kent",
    "Fullerton",
    "Denton",
    "Visalia",
    "McAllen"
]